import Head from 'next/head';
import Header from '../components/Header';
import Guide from '../components/Guide';

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Guide />
      </main>
    </div>
  );
};

export default Home;
